### PR TITLE
Milestone1

### PR DESCRIPTION
**Pull request by hemantso**
- setup the react app
- linter setup
-  deployed to Heroku [https://murmuring-castle-25802.herokuapp.com/](calculator)

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi @hemant-soni-vst-au4! You have done a nice job working on most of the requirements for this milestone! :clap: However, there is just one issue I'd like you to fix before moving forward:
- [x] Your current `live link` returns a `404` error. Please consider adding it to your README after fixing it since you will need it there eventually. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone1/app-deployed.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896085/))

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by hemantso** [comment]
now it is working fine

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi @hemant-soni-vst-au4  👋

**Good job so far here. 👌**

- [x] Please update your readme, remove the default readme and customize it to include a description of the project also include the link in your readme.

- [x] It is important you use the linters configuration used by other students. Kindly include a `.eslintrc` file and ensure your linters files conform to those in this [link](https://github.com/microverseinc/linters-config/tree/master/react-redux).


### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

**Pull request merged**
